apiVersion: v1
kind: Service
metadata:
  name: resultingappservice
  labels: 
    app: voting-app
spec:
  type: LoadBalancer
  selector:
    app: voting-app
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 80
