apiVersion: v1
kind: Service
metadata:
  name: votingappvoteservice
  labels: 
    app: voting-app
spec:
  type: NodePort
  selector:
    app: voting-app
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
