apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingappvote
  labels:
    app: voting-app
spec:
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      labels:
        app: voting-app
    spec:
      containers:
      - name: votingappvotecontainer
        image: dockersamples/examplevotingapp_vote
        ports:
          - containerPort: 80
